modLoader="javafml"
loaderVersion="${fml_range}"
license="GPL3"

[[mods]] #mandatory
modId="vanillaplustools" #mandatory
version="${version}"
displayName="Vanilla+ Tools" #mandatory
credits="LDT Team"
authors="LDT Team"
description='''
3x3 mining and digging tools in vanilla flavor
'''
[[dependencies.vanillaplustools]]
    modId="neoforge"
    type="required"
    versionRange="${forge_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.vanillaplustools]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_range}"
    ordering="NONE"
    side="BOTH"
